name: Build with Webpack

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Read version
      uses: ashley-taylor/read-json-property-action@v1.0
      with:
        path: ./package.json
        property: version

    - name: Build
      run: |
        npm install
        npm run build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/gm-requests.meta.js
          ./dist/gm-requests.user.js
